version: '3'

services:
  elasticsearch:
    image: elasticsearch:5.2.2
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - TZ=Europe/Paris
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
  kibana:
    image: kibana:5.2.2
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    environment:
      - TZ=Europe/Paris
    depends_on:
      - elasticsearch